title: Vivesh Tyagi 
# description: Cloud Specialist 
logo: "/image/headshot.png?raw=true"
theme: jekyll-theme-minimal_mistakes_skin

#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#theme: jekyll-theme
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme

github:
  is_project_page: false
