title: "Vivesh Tyagi"

defaults:
- scope:
    path: ""
    type: authors
  values:
    layout: author


collections:
  authors: Vivesh
    output: true
    permalink: /~:name


markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

sass:
  style:    expanded

plugins:
- jekyll-avatar

safe: true
lsi: false

github:
  is_project_page: false
