title: Vivesh Tyagi 
description: Cloud Specialist 

ang:                  en

accent_image:          /image/sidebar-bg.jpg
accent_color:          rgb(79,177,186)
theme_color:           rgb(25,55,71)

google_fonts:          Roboto+Slab:700|Noto+Sans:400,400i,700,700i
font:                  Noto Sans, Helvetica, Arial, sans-serif
font_heading:          Roboto Slab, Helvetica, Arial, sans-serif
font-code:             ui-monospace, Menlo, Monaco, "Cascadia Mono", "Segoe UI Mono", "Roboto Mono", "Oxygen Mono", "Ubuntu Monospace", "Source Code Pro", "Fira Mono", "Droid Sans Mono", "Courier New", monospace;


#theme: jekyll-theme-dark
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme

github:
  is_project_page: false
