title: Vivesh Tyagi 
# description: Cloud Specialist 
logo: "/image/headshot.png?raw=true"
## Cloud Platforms ![70%](https://progress-bar.dev/70)   Customer Experience ![100%](https://progress-bar.dev/100)   
## Leadership ![90%](https://progress-bar.dev/90) Enthusiast Learner ![100%](https://progress-bar.dev/100)
## Web Development ![70%](https://progress-bar.dev/70)     Internet Of Things ![50%](https://progress-bar.dev/50)
theme: jekyll-theme-minimal

#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#theme: jekyll-theme
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme
exclude:
        -  description
github:
  is_project_page: false
