title: Vivesh Tyagi 
description: Cloud Specialist 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0

#minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
#theme: jekyll-theme-minmal
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#- jekyll-remote-theme

github:
  is_project_page: false
